name       : python-jsonrpclib
version    : 0.4.1
release    : 7
source     :
    - https://github.com/tcalmant/jsonrpclib/archive/v0.4.1.tar.gz : 9dad474a2b90c70afe98ba5563781a4724e1c384cf66e43aa31934cae28b9cb0
homepage   : https://github.com/tcalmant/jsonrpclib
license    : Apache-2.0
component  : programming.python
summary    : This library is an implementation of the JSON-RPC specification (aka jsonrpclib-pelix)
description: |
    This library is an implementation of the JSON-RPC specification. It supports both the original 1.0 specification, as well as the new (proposed) 2.0 spec, which includes batch submission, keyword arguments, etc.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-simplejson
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
